<a href="https://colab.research.google.com/github/Kimeungseok/Kimeungseok/blob/main/ML_k_nearipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# k 근접법 머시러닝

In [1]:
import pandas as pd
aaa = pd.read_csv('iris2.csv')

                                                                                   # 문자 -> 숫자 변환(0,1)
                                                                                   # aaa['Class'] = aaa['Class'].map({'malignant':1, 'benign':0})

aaa.head(10)

iris  sepal length  sepal width  petal length  petal width
0  Iris-setosa           5.1          3.5           1.4          0.2
1  Iris-setosa           4.9          3.0           1.4          0.2
2  Iris-setosa           4.7          3.2           1.3          0.2
3  Iris-setosa           4.6          3.1           1.5          0.2
4  Iris-setosa           5.0          3.6           1.4          0.2
5  Iris-setosa           5.4          3.9           1.7          0.4
6  Iris-setosa           4.6          3.4           1.4          0.3
7  Iris-setosa           5.0          3.4           1.5          0.2
8  Iris-setosa           4.4          2.9           1.4          0.2
9  Iris-setosa           4.9          3.1           1.5          0.1

In [ ]:
# 결측치 확인 #
aaa.isnull().sum()

In [4]:
# features, 결과 정의 #

features = aaa[['sepal length','sepal width','petal length','petal width']]
judges = aaa['iris']

In [5]:
# 학습 데이터셋, Test 데이터셋 구분 #


from sklearn.model_selection import train_test_split

trset1, ttset1, trlabel1, ttlabel1 = train_test_split(features, judges, test_size=0.25, random_state=42)

print(len(trset1), len(ttset1))

112 38


In [6]:
# 데이터 정규화 #

from sklearn.preprocessing import StandardScaler

trans1 = StandardScaler()

trset1 = trans1.fit_transform(trset1)
ttset1 = trans1.fit_transform(ttset1)

# print(tr_set1)
# print(tt_set1)

In [7]:
# k 근접법 학습 #
from sklearn.neighbors import KNeighborsClassifier

model1 = KNeighborsClassifier(n_neighbors=2)
model1.fit(trset1, trlabel1)

KNeighborsClassifier(n_neighbors=2)

KNeighborsClassifier(n_neighbors=2)

In [8]:
# 학습 모델 성능 검사 #

accu_tr1 = model1.score(trset1, trlabel1)
accu_tt1 = model1.score(ttset1, ttlabel1)

print('학습데이터 정확도 : ', round(accu_tr1,3))
print('검증데이터 정확도 : ', round(accu_tt1,3))



학습데이터 정확도 :  0.964
검증데이터 정확도 :  0.947


In [11]:
# Confusion Matrix #

from sklearn.metrics import confusion_matrix
import sklearn.metrics as metrics
import numpy as np

import matplotlib.pyplot as plt
import seaborn

pre1 = model1.predict(ttset1)       # 예측 결과 #
print(pre1)

cm = confusion_matrix(pre1, ttlabel1)
print(cm)



['Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-setosa']
[[15  0  0]
 [ 0 11  2]
 [ 0  0 10]]


In [13]:
#  분류 리포트 확인 #

from sklearn.metrics import classification_report

c_report = classification_report(pre1, ttlabel1)
print(c_report)

# Precision :  Recal(Sensivity)

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        15
Iris-versicolor       1.00      0.85      0.92        13
 Iris-virginica       0.83      1.00      0.91        10

       accuracy                           0.95        38
      macro avg       0.94      0.95      0.94        38
   weighted avg       0.96      0.95      0.95        38



In [ ]:

gr_names = ["TN", "FP (type  II error)", "FN (type I error)", "TP"]
gr_counts = [value for value in cm.flatten()]

gr_per = [f"{value:.1%}" for value in cm.flatten()/np.sum(cm)]

labels = [f"{v1}\n{v2}\n({v3})" for v1, v2, v3 in zip(gr_names,gr_counts,gr_per)]
labels = np.asarray(labels).reshape(2.2)

seaborn.heatmap(cm, annot=labels, fmt='', cmap='viridis')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')

In [16]:
# 새로운 데이터에 대한 예측 #


import pandas as pd

bbb = pd.read_csv('iris2-new.csv')

# bbb.head()

from sklearn.preprocessing import StandardScaler

features2 = bbb[['sepal length','sepal width','petal length','petal width']]

trans1 = StandardScaler()                # 데이터 정규화 #
bbb = trans1.fit_transform(bbb)

pre1 = model1.predict(features2)         # 새로운 데이터 예측 #
print(pre1)

model1.predict_proba(features2)          # 새로운 데이터 예측 확률 #

['Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica']


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [ ]:
print(cm.shape)
print(labels.shape)

(3, 3)
(2, 2)


In [ ]:
# Confutions Matrix 이쁘게 꾸미기 #

gr_names = ["TN", "FP (type  II error)", "FN (type I error)", "TP"]
gr_counts = [value for value in cm.flatten()]

gr_per = [f"{value:.1%}" for value in cm.flatten()/np.sum(cm)]

labels = [f"{v1}\n{v2}\n({v3})" for v1, v2, v3 in zip(gr_names,gr_counts,gr_per)]

labels = np.asarray(labels).reshape(2,2)
labels


array([['TN\n15\n(39.5%)', 'FP (type  II error)\n0\n(0.0%)'],
       ['FN (type I error)\n0\n(0.0%)', 'TP\n0\n(0.0%)']], dtype='<U28')